name: Build

on:
  push:
    branches:
      - main

jobs:
  SyncTag:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.x # Run with latest stable Deno.

      - name: Cache Dependencies
        run: deno task cache

      - name: Bump Tag
        run: deno task bump-tag
